Collection Name: bookings

- _id: ObjectId (Unique identifier, auto-generated by MongoDB)
- room: ObjectId (Required, References 'Room' collection)
- customer: ObjectId (Required, References 'User' collection - the customer who made the booking)
- owner: ObjectId (Required, References 'User' collection - the owner of the booked room)
- checkInDate: Date (Required)
- checkOutDate: Date (Required)
- totalPrice: Number (Required)
- status: String (Enum: 'pending', 'confirmed', 'completed', 'cancelled', default: 'pending')
- createdAt: Date (Auto-generated timestamp)
- updatedAt: Date (Auto-generated timestamp)
