Collection Name: users

- _id: ObjectId (Unique identifier, auto-generated by MongoDB)
- email: String (Unique, Required, Trimmed, Lowercase)
- password: String (Required, Hashed)
- mobileNumber: String (Unique, Required, Trimmed)
- role: String (Required, Enum: 'customer', 'house_owner')
- createdAt: Date (Auto-generated timestamp)
- updatedAt: Date (Auto-generated timestamp)
